name: Release Please
description: Get a list of pull requests and send messages to reviewers for each PR.
author: mechiru

inputs:
  github-token:
    description: GitHub API token
    default: ${{ github.token }}
  repo:
    description: Target repository. Format is `owner/repo_name`.
    default: ${{ github.repository }}
  review-deadline:
    description: New Pull Request review deadline. The period is expressed in days and has a `d` suffix.
    default: 6d

outputs:
  prs:
    description: Pull Request information

runs:
  using: node20
  main: dist/index.js
